In [3]:
def printValue(s1, s2): #Defining a function to compare.
    len1 = len(s1)
    len2 = len(s2)
    if len1>len2:
        print(s1)
    elif len2>len1:
        print(s2)
    else:
        print(s1,'\n', s2)
        
printValue("one","three")

three


In [5]:
def CheckValue(n):   #Defining a function to check even or odd.
    if n%2 == 0:
        print("It is an even number!")
    else:
        print("It is an odd number!")
CheckValue(7)

It is an odd number!


In [10]:
def PrintDict(n):
    d = dict()
    for i in range(1,n+1):
        d[i] = i*i
    return d
    
PrintDict(3)
        

{1: 1, 2: 4, 3: 9}

In [11]:
list(map(lambda x: x**2, range(1,21)))

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

In [13]:
def printList():
    print(list(map(lambda x: x**2, range(1,21))))
    
printList()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [14]:
def printList():
    result = list(map(lambda x: x**2, range(1,21)))[:5]
    print(result[:5])
    
printList()

[1, 4, 9, 16, 25]


In [15]:
def printTuple():
    print(tuple(map(lambda x: x**2, range(1,21))))
    
printTuple()
    

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400)


In [16]:
t = (1,2,3,4,5,6,7,8,9,10)
len(t)

10

In [17]:
len(t)//2

5

In [18]:
x = t[:len(t)//2]
x

(1, 2, 3, 4, 5)

In [20]:
y = t[len(t)//2:]
y


(6, 7, 8, 9, 10)

In [21]:
t = (1,2,3,4,5,6,7,8,9,10)
result = []
for i in t:
    if i%2 == 0:
        result.append(i)
        
tuple(result)

(2, 4, 6, 8, 10)

In [22]:
tuple(filter(lambda x:x%2 == 0, t))

(2, 4, 6, 8, 10)

In [23]:
s = input('Please Enter: ')

Please Enter: yes


In [24]:
type(s)

str

In [32]:
s = input('Please Enter: ')

if s=='Yes' or s=='YES' or s=='yes':
    print('Wuhoo, Yes!')
else:
    print('Nope,Never happens!')

Please Enter: yes
Wuhoo, Yes!


In [28]:
s


'yes'

In [29]:
s.lower()

'yes'

In [30]:
s.lower().strip()

'yes'

In [33]:
if s.lower().strip() == "yes":
    print('Ok')
else:
    print('Not ok')

Ok


In [34]:
lst = list(range(1,11))
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
list(map(lambda x:x**2, filter(lambda i:i%2==0,range(1,11))))

[4, 16, 36, 64, 100]

In [37]:
#(********************************************************************)

In [38]:
#Numpy

import numpy as np

In [39]:
np

<module 'numpy' from 'C:\\Users\\navya Ranganath\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [44]:
lst = [[1,2,3],[5,6,7]] #Here we are getting a array of 2*3 size

In [46]:
array = np.array(lst)

In [47]:
array

array([[1, 2, 3],
       [5, 6, 7]])

In [48]:
array.shape #lets you know about the order of the matrix

(2, 3)

In [51]:
np.zeros((4,4)) #matrix of 0's

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((3,3)) #matrix of 1's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.eye(3) #identity matrix usage.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
array = np.arange(0,100) #range of list

In [68]:
np.linspace(1,10,10) #Gives the line space

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [69]:
array.shape

(100,)

In [72]:
array1 = array.reshape(10,10)

In [73]:
array1.shape

(10, 10)

In [76]:
np.random.random((5,5))

array([[0.7074501 , 0.91294889, 0.34467153, 0.13699895, 0.48607169],
       [0.36780774, 0.94806199, 0.53310358, 0.70932456, 0.91031729],
       [0.9769168 , 0.91407025, 0.19515042, 0.7782686 , 0.51762776],
       [0.98494301, 0.10919138, 0.15986018, 0.06906347, 0.91394745],
       [0.91688514, 0.33945269, 0.75486145, 0.33299899, 0.50669766]])

In [77]:
array.max()

99

In [78]:
array.min()

0

In [80]:
array1.argmax()

99

In [81]:
array1.argmin()

0

In [82]:
array[3]

3

In [84]:
a = array.reshape(10,10)
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
a[1,1]

11

In [86]:
a[2,3]

23

In [87]:
a[0:2,1:3] #To get a range of numbers,we use slicing operation

array([[ 1,  2],
       [11, 12]])

In [88]:
#To get from 22 to 44 
a[2:5,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

NameError: name 'rand' is not defined